import { Subscription, SubscriptionTemplate, User } from '../types';

export const mockUser: User = {
  id: 'user-1',
  email: 'demo@subsentry.com',
  name: 'Demo User',
  currencyPreference: '\u20B9',
  timezone: 'Asia/Kolkata',
  defaultReminderDays: 7,
  theme: 'light',
  createdAt: '2024-01-01T00:00:00Z',
  budget: {
    id: 'budget-1',
    userId: 'user-1',
    monthlyBudget: 10000,
    annualBudget: 120000,
    currency: '\u20B9',
    alertThreshold: 80,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  hasCompletedTutorial: true,
};

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    name: 'Netflix Premium',
    category: 'Streaming',
    amount: 649,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-01-15',
    nextRenewalDate: '2024-12-15',
    paymentMethod: 'Credit Card',
    notes: 'Family plan',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 7,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'sub-2',
    name: 'Spotify Premium',
    category: 'Streaming',
    amount: 119,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-02-01',
    nextRenewalDate: '2024-12-01',
    paymentMethod: 'UPI',
    notes: 'Individual plan',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 3,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'sub-3',
    name: 'Adobe Creative Cloud',
    category: 'SaaS',
    amount: 4299,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-01-10',
    nextRenewalDate: '2024-12-10',
    paymentMethod: 'Credit Card',
    notes: 'Photography plan',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 14,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'sub-4',
    name: 'Cult.fit Membership',
    category: 'Fitness',
    amount: 1499,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-03-01',
    nextRenewalDate: '2024-12-20',
    paymentMethod: 'Debit Card',
    notes: 'Elite membership',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 7,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'sub-5',
    name: 'GitHub Pro',
    category: 'SaaS',
    amount: 399,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-01-05',
    nextRenewalDate: '2024-12-05',
    paymentMethod: 'Credit Card',
    notes: 'Developer tools',
    status: 'active',
    reminderEnabled: false,
    reminderDaysBefore: 7,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'sub-6',
    name: 'Amazon Prime',
    category: 'Streaming',
    amount: 1499,
    currency: '\u20B9',
    billingCycle: 'annual',
    firstPaymentDate: '2024-01-20',
    nextRenewalDate: '2025-01-20',
    paymentMethod: 'UPI',
    notes: 'Annual subscription',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 14,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'sub-7',
    name: 'Microsoft 365',
    category: 'SaaS',
    amount: 4899,
    currency: '\u20B9',
    billingCycle: 'annual',
    firstPaymentDate: '2024-02-15',
    nextRenewalDate: '2025-02-15',
    paymentMethod: 'Credit Card',
    notes: 'Family plan with 1TB storage',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 30,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'sub-8',
    name: 'Notion Pro',
    category: 'SaaS',
    amount: 399,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-04-01',
    nextRenewalDate: '2024-12-18',
    paymentMethod: 'Credit Card',
    notes: 'Personal Pro plan',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 7,
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2024-04-01T00:00:00Z',
  },
  {
    id: 'sub-9',
    name: 'YouTube Premium',
    category: 'Streaming',
    amount: 129,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-05-10',
    nextRenewalDate: '2024-12-10',
    paymentMethod: 'UPI',
    notes: 'Ad-free experience',
    status: 'active',
    reminderEnabled: false,
    reminderDaysBefore: 7,
    createdAt: '2024-05-10T00:00:00Z',
    updatedAt: '2024-05-10T00:00:00Z',
  },
  {
    id: 'sub-10',
    name: 'Headspace',
    category: 'Fitness',
    amount: 399,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-03-15',
    nextRenewalDate: '2024-11-25',
    paymentMethod: 'Credit Card',
    notes: 'Meditation app',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 3,
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'sub-11',
    name: 'Zoom Pro',
    category: 'SaaS',
    amount: 1099,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-01-01',
    nextRenewalDate: '2024-11-28',
    paymentMethod: 'Credit Card',
    notes: 'Video conferencing',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 7,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'sub-12',
    name: 'Canva Pro',
    category: 'SaaS',
    amount: 499,
    currency: '\u20B9',
    billingCycle: 'monthly',
    firstPaymentDate: '2024-06-01',
    nextRenewalDate: '2024-11-22',
    paymentMethod: 'UPI',
    notes: 'Design tools',
    status: 'active',
    reminderEnabled: true,
    reminderDaysBefore: 5,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
];

export const subscriptionTemplates: SubscriptionTemplate[] = [
  {
    id: 'template-netflix',
    name: 'Netflix Premium',
    description: '4 screens of Ultra HD streaming',
    icon: '\uD83C\uDFAC',
    category: 'Streaming',
    defaultBillingCycle: 'monthly',
    suggestedAmount: 649,
    currency: '\u20B9',
    paymentMethod: 'Credit Card',
    priceRange: { min: 499, max: 799 },
    tags: ['Entertainment', 'Family'],
    noteHint: 'Share plans with family to reduce per-person cost.',
  },
  {
    id: 'template-spotify',
    name: 'Spotify Premium',
    description: 'Ad-free music with offline downloads',
    icon: '\uD83C\uDFA7',
    category: 'Streaming',
    defaultBillingCycle: 'monthly',
    suggestedAmount: 119,
    currency: '\u20B9',
    paymentMethod: 'UPI',
    priceRange: { min: 119, max: 179 },
    tags: ['Music', 'Personal'],
  },
  {
    id: 'template-amazon-prime',
    name: 'Amazon Prime',
    description: 'Shopping + Video bundle',
    icon: '\uD83D\uDCE6',
    category: 'Streaming',
    defaultBillingCycle: 'annual',
    suggestedAmount: 1499,
    currency: '\u20B9',
    paymentMethod: 'UPI',
    priceRange: { min: 1499, max: 1799 },
    tags: ['Bundle', 'Shopping'],
    noteHint: 'Annual plans cost less than monthly top-ups.',
  },
  {
    id: 'template-youtube-premium',
    name: 'YouTube Premium',
    description: 'Ad-free YouTube & Music',
    icon: '\u25B6\uFE0F',
    category: 'Streaming',
    defaultBillingCycle: 'monthly',
    suggestedAmount: 129,
    currency: '\u20B9',
    paymentMethod: 'Credit Card',
    priceRange: { min: 129, max: 189 },
    tags: ['Video', 'Music'],
  },
  {
    id: 'template-adobe',
    name: 'Adobe Creative Cloud',
    description: 'Photography bundle essentials',
    icon: '\uD83C\uDFA8',
    category: 'SaaS',
    defaultBillingCycle: 'monthly',
    suggestedAmount: 4299,
    currency: '\u20B9',
    paymentMethod: 'Credit Card',
    priceRange: { min: 2399, max: 4899 },
    tags: ['Design', 'Work'],
  },
  {
    id: 'template-gym',
    name: 'Cult.fit Membership',
    description: 'Unlimited classes & gym access',
    icon: '\uD83D\uDCAA',
    category: 'Fitness',
    defaultBillingCycle: 'monthly',
    suggestedAmount: 1499,
    currency: '\u20B9',
    paymentMethod: 'Debit Card',
    priceRange: { min: 999, max: 2499 },
    tags: ['Wellness'],
    noteHint: 'Track if you pause membership seasonally.',
  },
];
